# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ContatosSwift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContatosSwift


	pod 'Alamofire', '~> 3.4'
    pod 'AlamofireImage', '~> 2.4'


end
